#!/usr/bin/env ruby

require "rails"
# require "thor"
require "bundler/setup"
require "pixelpro_sdk"

name = "pixel"
name = ARGV.first if ARGV.first

pixel_controller = PixelproSdk::AddPage.new
pixel_controller.add_controller_file name
pixel_controller.append_route name
